apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: unacceptable-canid-dotnet-basic
  janus-idp.io/tekton: unacceptable-canid-dotnet-basic
  backstage.io/kubernetes-id: unacceptable-canid-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-e2e-ci 
  app.kubernetes.io/part-of: unacceptable-canid-dotnet-basic
resources: 
- deployment.yaml
- route.yaml
- service.yaml
